app/routes/page/loginPage.tsx

Dev merge test

---

app/api/notice.ts
app/components/admin/notices/formComponent.tsx
app/components/admin/notices/listComponent.tsx
app/root.tsx
app/routes.ts
app/routes/admin/notices/addPage.tsx
app/routes/admin/notices/detailPage.tsx
app/routes/admin/notices/editPage.tsx
app/routes/admin/notices/listPage.tsx
app/types/notice.d.ts
package-lock.json
package.json
vite.config.ts

[🌱feat] 공지사항 프론트엔드 기능 구현 
---
---
- 레이아웃 처리 미구현
- 이미지 안보이는 현상 수정
- .env는 Commit X
---
- 레이아웃 처리
---
---
---
---

feat(admin/notice): 공지사항 프론트엔드 기능 구현 

---

app/api/authAPI.ts
app/api/googleAPI.ts
app/components/auth/loginComponent.tsx
app/instance/axiosInstance.ts
app/routes.ts
package-lock.json
package.json

access 토큰 갱신 구현 수정해야함
로그아웃 구현 해야함

[📦 refactor] 구글 로그인 인증 쿠키 저장

---

app/components/products/detailComponent.tsx
app/types/products.d.ts

- description (상세 설명) 받아오도록 수정

[📦 refactor] 상품 상세 보기 구현

---

app/api/signupAPI.ts
app/components/auth/loginComponent.tsx
app/components/common/loadingComponent.tsx
app/instance/axiosInstance.ts

[📦 refactor] 회원가입 후 자동로그인 기능, 로딩컴포넌트 추가

---

app/components/barcode/barcodeScannerComponent.tsx
app/components/common/modalComponent.tsx
app/routes.ts
app/routes/barcode/scanPage.tsx
package-lock.json
package.json

- Common에 모달 컴포넌트 추가했음, 디자인은 수정 필요.
- 콘솔에 바코드 넘버 출력했으나, 추후 해당 정보로 상품조회 기능 추가

[🌱 feat] ZXing 바코드 촬영 API 적용

---

app/api/productsAPI.ts
app/components/products/listComponent.tsx
app/layout/productLayout.tsx
app/routes.ts
app/routes/products/detailPage.tsx
app/routes/products/listPage.tsx
app/types/products.d.ts
package-lock.json
package.json

- 자동 숨김 헤더(Autohide Header) 적용
- Encountered two children with the same key 경고 해결

[📦 refactor] 상품 랭킹 화면 디자인 및 검색/카테고리/정렬 로직 적용

---

app/components/products/detailComponent.tsx
app/types/products.d.ts

- products/detailPage 로딩 시 is_liked도 받도록 수정
- 낙관적 업데이트(Optimistic Update) 사용하여 좋아요 버튼 구현

Feature/products[🌱 feat] 상품 좋아요 기능 구현

---

app/components/products/listComponent.tsx
app/routes/products/listPage.tsx

- 카테고리 내용 변경에 따른 디자인 수정
- 상품 랭킹 사진 비율 고정

[📦 refactor] 카테고리 개선

---

app/api/productsAPI.ts
app/components/products/detailComponent.tsx
app/components/products/listComponent.tsx
app/layout/appLayout.tsx
app/routes/products/listPage.tsx

- /ranking, /{barcode} 페이지에 appLayout 적용
- 카테고리/정렬/검색 드롭다운 통합 및 위치 수정
- 상품 좋아요 기능 제대로 작동하도록 수정

[📦 refactor] appLayout 적용

---

app/routes/products/detailPage.tsx
app/routes/products/listPage.tsx

- /ranking, /{barcode} 페이지에 appLayout, bottomNavComponent 적용
- 카테고리/정렬/검색 드롭다운 통합 및 위치 수정
- 상품 좋아요 기능 제대로 작동하도록 수정

[📦 refactor] appLayout, bottomNavComponent 적용

---

app/api/myPageAPI.ts
app/layout/appLayout.tsx
app/routes/users/favoritesPage.tsx

- 필터링 드롭다운 바 제거하여 랭킹 페이지와 유사하게 구현

[🌱 feat] mypage/favorites 구현

---

app/api/myPageAPI.ts
app/components/users/myPageComponent.tsx
app/components/users/myPageEditComponent.tsx
app/components/users/passwordChangeSection.tsx
app/hooks/users/useMyPageEdit.ts
app/hooks/users/useNicknameChange.ts
app/hooks/users/usePasswordChange.ts
app/layout/appLayout.tsx
app/types/users.d.ts

- 비밀번호 수정 가능
- 닉네임 변경 가능
- 이미지 수정 가능
- 태그 수정 가능

[🌱 feat] 프로필 수정 기능

---

app/api/reviews/adminReviewAPI.ts
app/api/reviews/reviewAPI.ts
app/components/admin/reports/listComponent.tsx
app/components/admin/reports/reportFilterBar.tsx
app/components/admin/reviews/listComponent.tsx
app/components/admin/reviews/readComponent.tsx
app/components/admin/reviews/reviewDetailInfo.tsx
app/components/admin/reviews/reviewFilterBar.tsx
app/components/admin/reviews/reviewMetaInfo.tsx
app/components/admin/users/auDetailComponent.tsx
app/components/admin/users/auDetailHeaderComponent.tsx
app/components/reviews/addComponent.tsx
app/components/reviews/modifyComponent.tsx
app/components/reviews/previewComponent.tsx
app/components/reviews/productListComponent.tsx
app/hooks/useReviewReport.ts
app/routes.ts
app/routes/admin/reports/listPage.tsx
app/routes/admin/reviews/readPage.tsx
app/routes/reviews/addPage.tsx
app/routes/reviews/detailPage.tsx
app/routes/reviews/modifyPage.tsx
app/routes/reviews/productListPage.tsx
app/types/reviews.d.ts

- AdminReview, AdminReviewReport 화면 구현

[🌱 feat] 관리자 리뷰 관리, 관리자 리뷰 신고 관리 구현

---

app/api/users/adminUsersAPI.ts
app/components/admin/users/auDetailComponent.tsx
app/components/admin/users/auDetailHeaderComponent.tsx
app/components/admin/users/auDetailProfileComponent.tsx
app/components/admin/users/auDetailReveiwsComponent.tsx
app/components/admin/users/auListComponent.tsx
app/components/users/myPageEditComponent.tsx
app/components/users/signupProfileComponent.tsx
app/hooks/users/useUserStatusUpdater.ts
app/routes.ts
app/routes/admin/users/auDetailPage.tsx
app/types/users.d.ts
app/util/countryUtils.ts
package.json

- 프로필 상세보기
- 어드민에서 사용자별 리뷰 보기 추가

[🌱 feat] 어드민 사용자 상세보기 

---

app/components/admin/products/listComponent.tsx
app/routes/products/rankingPage.tsx
app/routes/products/searchPage.tsx

- 상품 목록에서 SoftDelete 되어 있는 상품에 대한 필터링 기능 개선
- 삭제된 상품이 있어도 페이지에서 10개씩 보여줄 수 있도록 수정함

[🐛 fix] 삭제된 상품 페이징 문제 해결

---

app/components/admin/users/auDetailComponent.tsx
app/components/admin/users/auListComponent.tsx
app/routes/admin/users/adminUsersListPage.tsx

[📦 refactor] 뒤로가기 유지

---

app/api/products/productsAPI.ts
app/layout/appLayout.tsx
app/routes/products/recommendedPage.tsx

- 상품 태그에 대해 사용자 태그로 검색하여 목록에 보여주는 기능 구현

[🌱 feat] 상품 추천 페이지 구현

---

app/components/admin/users/auListComponent.tsx
app/components/admin/users/statusChangeModal.tsx
app/components/main/bottomNavComponent.tsx
app/hooks/users/useUserStatusUpdater.ts
app/routes/admin/users/adminUsersListPage.tsx
app/types/users.d.ts

[📦 refactor] userStatus 변경 기능 수정
---
---
- 정상적으로 성공했을 때만 화면을 갱신
---
---

[📦 refactor] userStatus 변경 기능 수정

---

app/components/users/myPageComponent.tsx
app/routes.ts
app/routes/auth/logoutPage.tsx

[🌱 feat] 로그아웃 기능 추가
---
---
- 로그아웃 기능 추가하고 마이페이지에서 로그아웃 할 수 있도록 연결
---
---

[🌱 feat] 로그아웃 기능 추가

---

app/components/admin/reports/listComponent.tsx
app/components/admin/reviews/listComponent.tsx
app/components/admin/reviews/readComponent.tsx
app/components/admin/users/auDetailHeaderComponent.tsx
app/components/admin/users/auListComponent.tsx
app/components/products/listComponent.tsx
app/components/reviews/productListComponent.tsx
app/components/reviews/userListComponent.tsx
app/components/users/myPageComponent.tsx
app/layout/appLayout.tsx
app/routes/admin/reports/listPage.tsx
app/types/reviews.d.ts
app/util/FloatingActionButtons.tsx

[📦 refactor] 리뷰 리스트 위아래 버튼 추가, 리뷰 헤더 변경
---
---
---
---

[📦 refactor] 리뷰 리스트 위아래 버튼 추가, 리뷰 헤더 변경

---

app/api/myPageAPI.ts
app/api/signupAPI.ts
app/components/users/myPageComponent.tsx
app/components/users/myPageEditComponent.tsx
app/components/users/signupComponent.tsx
app/components/users/signupProfileComponent.tsx
app/components/users/signupTagComponent.tsx
app/hooks/users/useAccountDelete.ts
app/hooks/users/useAutoNickname.ts
app/hooks/users/useEmailChecker.ts
app/hooks/users/useGetProfile.ts
app/hooks/users/useMyPageEdit.ts
app/hooks/users/useNicknameChecker.ts
app/routes/users/myPageEditPage.tsx
app/routes/users/myPagePage.tsx
app/types/users.d.ts

[📦 refactor] 마이페이지 및 회원가입 개선

---

app/api/inquiriesAPI.ts
app/components/admin/inquiries/detailComponent.tsx
app/components/admin/inquiries/inquiryDetailInfo.tsx
app/components/admin/inquiries/inquiryFilterBar.tsx
app/components/admin/inquiries/inquiryMetaInfo.tsx
app/components/admin/inquiries/listComponent.tsx
app/components/admin/inquiries/replyAddInfo.tsx
app/components/admin/inquiries/replyEditInfo.tsx
app/hooks/inquiries/useInquiryMutation.tsx
app/routes/admin/inquiries/listPage.tsx
app/routes/inquiries/addPage.tsx
app/routes/inquiries/editPage.tsx
app/types/inquiries.d.ts

[🌱 feat] 어드민페이지 문의사항 답변 구현
---
- UI 구현 예정
---
---
---

[🌱 feat] 어드민페이지 문의사항 답변 구현

---

app/api/points/adminPointsAPI.ts
app/api/points/pointsAPI.ts
app/routes/points/pointLogsPage.tsx
app/routes/points/userCouponPage.tsx
app/routes/users/myPagePage.tsx

[🌱 feat] 쿠폰 개수 api 생성, 연결
---
- 쿠폰 개수 api 생성
- 로그, 쿠폰함 sort 변경
---
---
---

[🌱 feat] 쿠폰 개수 api 생성, 연결

---

app/api/points/pointsAPI.ts
app/components/admin/points/listComponent.tsx
app/components/admin/points/readComponent.tsx
app/components/points/storeListComponent.tsx
app/components/points/userCouponComponent.tsx
app/routes/points/couponModal.tsx
app/routes/points/storeListPage.tsx

[📦 refactor] 디자인 수정
---
- 모달창 추가, 수정
- 사진 크기 조정
---
---
---

[📦 refactor] 디자인 수정

---

app/api/notices/adminNoticesAPI.ts
app/components/admin/notices/listComponent.tsx
app/components/admin/notices/noticeFilterBar.tsx
app/routes/admin/notices/listPage.tsx
app/types/notice.d.ts

제목
[📦 refactor] 관리자 공지사항 페이지 개선
---
- 검색 기능 구현
- Pagination 사용하도록 수정
- axiosInstance -> axiosInstanceAdmin 적용
---
---
---

[📦 refactor] 관리자 공지사항 페이지 개선

---

app/api/auth/authAPI.ts
app/instance/axiosInstanceAdmin.ts
app/routes.ts

[🌱 feat] 어드민 권한 분리

---

app/api/products/adminProductsAPI.ts
app/components/admin/products/detailComponent.tsx
app/components/admin/products/listComponent.tsx
app/components/main/RankingComponent.tsx
app/components/main/RecommendComponent.tsx
app/components/products/detailComponent.tsx
app/components/products/listComponent.tsx
app/components/reviews/addComponent.tsx
app/types/products.d.ts

[📦 refactor] 상품 목록 페이지 개선
---
- 이미지 webp로 변환
- 상품 목록 조회 시 썸네일 적용
---
---
---

[📦 refactor] 상품 목록 페이지 개선

---

app/components/admin/inquiries/inquiryDetailInfo.tsx
app/components/admin/inquiries/listComponent.tsx
app/contexts/AdminAuthContext.tsx

제목
---
---
- [] 새로운 기능 추가
---
---

[📦 refactor] 어드민 인증 상태 개선 및 문의사항 개선

---

app/api/products/adminProductsAPI.ts
app/components/admin/notices/noticeFilterBar.tsx
app/components/admin/products/detailComponent.tsx
app/components/admin/products/formComponent.tsx
app/components/admin/products/productFilterBar.tsx
app/routes/admin/products/addPage.tsx
app/routes/admin/products/detailPage.tsx
app/routes/admin/products/editPage.tsx
app/routes/admin/products/listPage.tsx

[📦 refactor] 상품 업로드 로직 수정
---
- 썸네일 변환 기능 추가
- url 직접 입력 대신, 이미지 필수로 첨부 해야 하도록 수정
- webp 변환은 아직 안됨
---
---
---

[📦 refactor] 상품 업로드 로직 수정

---

app/api/reviews/reviewAPI.ts
app/components/reviews/productListComponent.tsx
app/routes/reviews/productListPage.tsx
app/types/reviews.d.ts

[🌱 feat] 리뷰 요약 조회 기능 구현
---
- 긍정, 부정 리뷰 요약 불러오기
- 긍정 리뷰 비율 표시
- 백엔드와 연결
---
---
---

[🌱 feat] 리뷰 요약 조회 기능 구현

---

.gitignore
app/components/chatbot/chatComponent.tsx

[🐛 fix] AI챗봇 정확도 개선
---
- 문자열답변 타입 조건 개선
---
---
---

[🐛 fix] AI챗봇 정확도 개선

---

app/api/points/pointsAPI.ts
app/routes/points/storeListPage.tsx

[🐛 fix] 쿠폰 구매 오류 수정
---
- 사용자, 관리자 read 로직 분리
---
---
---

[🐛 fix] 쿠폰 구매 오류 수정

---

app/components/admin/inquiries/listComponent.tsx

[📦 refactor] hydration error Fix
---
- col 행에 공백 제거
---
---
---

[📦 refactor] hydration error Fix

---

app/api/points/pointsAPI.ts
app/components/points/couponModal.tsx
app/components/points/storeListComponent.tsx
app/routes.ts
app/routes/points/storeListPage.tsx

[📦 refactor] 사용자 포인트 조회 api 추가 
---
- 포인트상점 사용자 포인트 표시
- 디자인 수정
---
---
---

[📦 refactor] 사용자 포인트 조회 api 추가 

---

app/components/main/RecommendComponent.tsx

[🐛 fix] 메인 자동 슬라이드
---
- 홀수인 경우 슬라이드 안되는 부분 수정
---
---
---

[🐛 fix] 메인 자동 슬라이드

---

app/api/auth/authAPI.ts
app/components/main/RecommendSkeleton.tsx
app/hooks/auth/useAuthContext.ts
app/layout/appLayout.tsx
app/routes.ts
app/routes/appMainPage.tsx
app/util/countryUtils.ts

[🐛 fix] 로그인 회원 체크
---
---
---
---

[🐛 fix] 로그인 회원 체크

---

app/components/admin/points/listComponent.tsx
app/components/chatbot/chatComponent.tsx
app/components/chatbot/welcomeComponent.tsx

제목
[📦 refactor] 챗봇 영어로 변경
---
- 챗봇 ui 영어로 변경
- 어드민 포인트 사진 안보이는거 수정
---
---
---

[📦 refactor] 챗봇 영어로 변경

---

app/components/admin/users/auListComponent.tsx
app/components/users/myPageComponent.tsx
app/hooks/users/useLanguageChange.ts
app/routes/admin/users/adminUsersListPage.tsx
app/routes/appMainPage.tsx

[🌱 feat] 언어 설정 모달
---
- 언어 설정하는 모달 만들기
---
---
---

[🌱 feat] 언어 설정 모달

---

app/api/points/adminPointsAPI.ts
app/components/admin/points/editComponent.tsx
app/types/points.d.ts

제목
[🐛 fix] 어드민 판매중단, 시작 오류 개선
---
- 포인트 어드민 판매중단, 시작 버튼 오류 개선
---
---
---

[🐛 fix] 어드민 판매중단, 시작 오류 개선

---

app/components/admin/reports/listComponent.tsx
app/components/main/RankingComponent.tsx
app/components/main/RecommendComponent.tsx
app/components/main/RecommendSkeleton.tsx
app/components/main/bottomNavComponent.tsx
app/components/main/menuGridComponent.tsx
app/components/users/myPageComponent.tsx
app/components/users/myPageEditComponent.tsx
app/components/users/passwordChangeSection.tsx
app/hooks/users/useAccountDelete.ts
app/hooks/users/useLanguageChange.ts
app/hooks/users/useMyPageEdit.ts
app/i18n.ts
app/routes/appMainPage.tsx
app/routes/auth/logoutPage.tsx
app/routes/notices/detailPage.tsx
app/routes/notices/listPage.tsx
app/util/loading/noticeLoading.tsx
app/util/swal/customSwal.css

[🌱 feat] 정적 데이터 국제화 적용 - 마이페이지, 메인
---
- i18n.ts 파일에 번역된 정적 데이터 나열
---
---
---

[🌱 feat] 정적 데이터 국제화 적용 - 마이페이지, 메인

---

app/components/auth/loginComponent.tsx
app/i18n.ts

[🌱 feat] 로그인 언어 설정

---

app/api/chatbot/chatbotAPI.ts
app/components/chatbot/chatComponent.tsx
app/components/chatbot/productRecommendComponent.tsx
app/components/chatbot/welcomeComponent.tsx
app/routes/chatbot/chatbotPage.tsx

[🌱 feat] 세션 초기화 로직 추가
---
- 세션 초기화 로직 추가
- 사용자 언어별 에러 메시지 추가
---
---
---

[🌱 feat] 세션 초기화 로직 추가

---

app/layout/appLayout.tsx

[📦 refactor] 레이아웃 문구 수정
---
---
---
---

[📦 refactor] 레이아웃 문구 수정

---

app/hooks/push/usePushPermissionModal.tsx
public/offline.html
public/sw.js

[📦 refactor] 외부 api 요청에 대한 서비스워커 개선 및  푸시 모달 디자인 개선
---
- 외부 api 요청에 대해 credentials: "include"로 보내도록 수정
---
---
---

[📦 refactor] 외부 api 요청에 대한 서비스워커 개선 및  푸시 모달 디자인 개선

---

app/api/barcode/barcodeAPI.ts
app/components/barcode/barcodeScannerComponent.tsx
public/sw.js

[📦 refactor] 오프라인 상태에서의 서비스웨어 개선
---
- 일부 캐싱 오류 해결
---
---
---

[📦 refactor] 오프라인 상태에서의 서비스웨어 개선

---

app/api/map/mapAPI.ts
app/components/chatbot/welcomeComponent.tsx
app/components/map/mapContainerComponent.tsx
app/routes/map/mapPage.tsx

[📦 refactor] 지도 언어설정 적용
---
- 지도 언어설정 적용
- 길찾기 에러 처리
---
---
---

[📦 refactor] 지도 언어설정 적용

---

app/api/users/myPageAPI.ts
app/routes/users/favoritesPage.tsx

[📦 refactor] tbl_product_base 분리 및 다국어 검색 기능 구현
---
- 찜한 상품 다국어 수정
---
---
---

[📦 refactor] tbl_product_base 분리 및 다국어 검색 기능 구현
